name = "notion-autoblog"
main = "../../../modules/upvote/cloudflare/worker.py"
compatibility_date = "2025-12-09"
compatibility_flags = ["python_workers"]
workers_dev = true

[assets]
directory = "../public"
binding = "ASSETS"
not_found_handling = "none"

[[kv_namespaces]]
binding = "UPVOTES"
id = "${UPVOTE_KV_NAMESPACE}"
